name: Hi there ;)
description: Blogging about react, js and architecture, UI and UX
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: javascript
    css_class   : 'syntax'
logo: false
paginate: 15
baseurl:
domain_name: 'http://miedziak.io'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]


# Details for the RSS feed generator
url:            'http://miedziak.io'
author:         'Łukasz Miedziński'
