name: Hi there ;)
description: Blogging react, js architecture, UI and UX
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://miedziak.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]


# Details for the RSS feed generator
url:            'http://miedziak.io'
author:         'Łukasz Miedziński'
